default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: 127.0.0.1
  port: 3306

production:
  <<: *default
  database: test_app_production


development:
  <<: *default
  database:  test_app_development

test:
  <<: *default
  database: test_app_test
