# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2def6212db26da7282ed4b32eaf013f88c410518951557d5a7b40d0819f4ee76dc7c144806c73c0fc4e408a683f4dad714d9c62909c99646c13d953c070d98c6

test:
  secret_key_base: 0aad07530807069ed22723f3820ac07b8482f4a04362d52811473e64e96f5544c92d817556cacfa1148014f45f2ff113359cf53f05b6750088486ebb96443829

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
